# Generated by Django 4.2.3 on 2023-07-23 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('confirmed_password', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
    ]
