# Generated by Django 4.2.3 on 2023-08-10 17:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names_of_client', models.CharField(max_length=200)),
                ('momo_pay_code', models.CharField(default='260954', max_length=10)),
                ('confirmation_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('simple_description', models.CharField(max_length=50)),
                ('detailed_description', models.CharField(max_length=500)),
                ('image', models.ImageField(max_length=2080, upload_to='path/to/your/images/')),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=500)),
                ('phone_number', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='base_app.signup')),
            ],
        ),
    ]
