# Generated by Django 4.2.3 on 2023-07-23 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='confirmed_password',
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
