# Generated by Django 4.2.3 on 2023-08-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_location_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
