# Generated by Django 4.2.3 on 2023-07-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_remove_signup_confirmed_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=500)),
            ],
        ),
    ]
