# Generated by Django 4.2.3 on 2023-08-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_products_alter_location_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names_of_client', models.CharField(max_length=200)),
                ('momo_pay_code', models.CharField(default='260954', max_length=10)),
                ('confirmation_code', models.CharField(max_length=10)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.signup')),
            ],
        ),
    ]
