# Generated by Django 4.2.3 on 2023-08-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='momo_pay_code',
            field=models.CharField(auto_created='260954', max_length=10),
        ),
    ]
