# Generated by Django 4.2.3 on 2023-08-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_payments_momo_pay_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='product_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='base_app.products'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='momo_pay_code',
            field=models.CharField(default='260954', max_length=10),
        ),
    ]
